### ISSUE TITLE
Release of R3M-DROID Model?

### ISSUE THREAD

**Issue by juseonghan** [luccachiang/robots-pretrain-robots#1]
Hello, thank you for your impressive work - great job! I was wondering if you were planning on releasing the model weights for the re-trained R3M model on DROID. Thank you!

**Comment by luccachiang** [comment]
Hi, I have updated our [huggingface repo](https://huggingface.co/GqJiang/robots-pretrain-robots/) and added the weights. Please refer to `mcr.load()` to load the model. Feel free to have a try :)

**Comment by juseonghan** [comment]
Great, thank you for the prompt response!
