### ISSUE TITLE
Grad-CAM Visualization

### ISSUE THREAD

**Issue by juseonghan** [luccachiang/robots-pretrain-robots#2]
Hello! For the Grad-CAM visualizations in your paper, did you just use `targets = None` and vanilla GradCAM from the pytorch-grad-cam library? Thanks!

**Comment by guangnianyuji** [comment]
Yes, we just use `targets = None` and vanilla GradCAM from the pytorch-grad-cam library (https://github.com/jacobgil/pytorch-grad-cam).

**Comment by juseonghan** [comment]
Great thanks!
