### ISSUE TITLE
Import Error in the MCR initialize file

### ISSUE THREAD

**Issue by yyardi** [luccachiang/robots-pretrain-robots#3]
Hello,

Great work with this encoder! My team and I are currently analyzing its performance in visuomotor policies for a survey! Having said that, after cloning the Git, I ran into a quick issue I would like to point out.

### On line 6 of `mcr/__init__.py` 
`from models.models_mcr import MCR` is undefined and needs to be `from mcr.models.models_mcr import MCR`

If you wish to keep this import, the above change is necessary. Otherwise, this import is never used anyway, so it's best to remove it. Thank you!

**Comment by luccachiang** [comment]
Thank you for your interest and suggestion. I have fixed the bug. If you have any other suggestions or requirements, don't hesitate to get in touch with me.
