### ISSUE TITLE
MVP weights available?

### ISSUE THREAD

**Issue by ankile** [luccachiang/robots-pretrain-robots#4]
Hey, awesome project!

Quick question: do you have the MVP model weights available somewhere? The weights have disappeared from their storage location specified in the repo...

Best, Lars

**Comment by luccachiang** [comment]
Hi Lars,

Thanks for your inquiry. Unfortunately, the MVP model weights are currently not available on our server. I will search somewhere else to see if I have a backup. If you need robotic representations, you can explore some alternative options:)

Guangqi
