### ISSUE TITLE
Analysis code

### ISSUE THREAD

**Issue by ankile** [luccachiang/robots-pretrain-robots#5]
Oh, also, any chance you can share the code you used for making the different analyses and visualizations? Would be very helpful for the community for sure!

Best, Lars

**Comment by luccachiang** [comment]
Hi Lars,

Thanks for your interest. We're actively working on cleaning up the codebase. It may be helpful to refer to [this issue](https://github.com/luccachiang/robots-pretrain-robots/issues/2) to visualize Grad-CAM figures to analyze.

Best regards,
Guangqi

**Comment by ankile** [comment]
Okay, perfect, thank you. That's the approach we've been taking as well, so just wanted to see some of the nuances of interacting with the different models you've analyzed in the paper. Feel free to let me know once you release the full code!
